% Visualize pre vs post conditioning EP waveforms at selected stim levels
% for a configurable list of (subject, channel, condition) cases.
%
% Produces one figure per case with a 2 x length(stimInterest) tiled layout:
%   Row 1: mean only (pre vs post), one panel per stim level of interest
%   Row 2: mean + 95% CI (pre vs post), one panel per stim level of interest
%
% The default cases below showcase depression at stim levels 3-4, but the
% script is fully general: edit `cases`, `subjectBlocks`, and `stimInterest`
% for any pre/post comparison at any stim level(s).
%
% Source of depression-case default: R_output/modulation_depression_levels34.csv
% (generated by dose_response_R_script_trim_conditions.R).
%
% Same infrastructure as visualize_EP_by_stimlevel.m and
% analyze_EP_compare_multiple_blocks.m (prepare_EP_blocks, plotBTLError).

close all; clear; clc
Z_ConstantsDBS_PairedPulse;
matlab_dir = 'MATLAB_Converted';
experiment = 'EP_Measurement';

% Analysis flags (match visualize_EP_by_stimlevel.m defaults)
avgTrials = 0; savePlot = 1; screenBadChans = 0; plotCondAvg = 0;
plotPkTr = 0; tryArtifact = 0; chanReref = 1; rerefMode = 'none';
numAvg = 3;

% --- USER CONFIG ------------------------------------------------------
% Stim levels of interest (1-indexed into stimLevelUniq). Default shows
% levels 3 and 4 but any subset works, e.g. [1 2 3 4] or just [3].
stimInterest = [3 4];

% Cases to plot. Columns: sid | preBlock | postBlock | condLabel | channel
% Default = top depression cases at stim 3-4 from
% modulation_depression_levels34.csv; replace with any pre/post comparison.
cases = {
    '9f852', 2, 3, 'A/B 25 ms',  4;   % -78% at stim 3, -70% at stim 4
    '68574', 6, 7, 'A/A 200 ms', 7;   % -27% at stim 3, -16% at stim 4
    '41a73', 5, 6, 'A/A 200 ms', 5;   %  mild depression at stim 4
    };

% Subject-level block lists that cover all blocks referenced in `cases`.
% Must match R_config_files/subj_<sid>.R blockIntPlot for the subject.
% Add an entry for any new subject referenced in `cases`.
subjectBlocks = containers.Map;
subjectBlocks('9f852') = [2 3 4 5 6 7 10 11 12];
subjectBlocks('68574') = 1:11;
subjectBlocks('41a73') = 1:10;

% Plot axis limits and colors
xLimMs  = [-10 70];
yLimUV  = [-350 350];
preCol  = [0.30 0.30 0.30];
postCol = [0.85 0.33 0.10];
% --- END USER CONFIG --------------------------------------------------

% Cache prepared data by subject so prepare_EP_blocks runs once per sid
dataCache = containers.Map;

for c = 1:size(cases, 1)
    sid       = cases{c, 1};
    preBlock  = cases{c, 2};
    postBlock = cases{c, 3};
    condLabel = cases{c, 4};
    chanInt   = cases{c, 5};

    if ~isKey(subjectBlocks, sid)
        warning('No subjectBlocks entry for %s; skipping case %d', sid, c);
        continue
    end

    if ~isKey(dataCache, sid)
        blocks = subjectBlocks(sid);
        chanIntList = unique([cases{strcmp(cases(:,1), sid), 5}]);
        legendText = repmat({''}, 1, length(blocks));
        fprintf('\n=== Preparing %s (blocks: %s) ===\n', sid, num2str(blocks));
        prepare_EP_blocks
        dataCache(sid) = struct( ...
            'epochsEPblock', {epochsEPblock}, ...
            'tEpoch',        tEpoch, ...
            'stimLevelUniq', stimLevelUniq, ...
            'tBegin',        tBegin, ...
            'tEnd',          tEnd, ...
            'blocks',        blocks);
    end

    entry = dataCache(sid);
    preIdx  = find(entry.blocks == preBlock);
    postIdx = find(entry.blocks == postBlock);
    if isempty(preIdx) || isempty(postIdx)
        warning('Missing block for %s: pre=%d, post=%d', sid, preBlock, postBlock);
        continue
    end

    fprintf('  Plotting %s chan %d: block %d (pre) vs block %d (post, %s)\n', ...
        sid, chanInt, preBlock, postBlock, condLabel);

    nStim = length(stimInterest);
    figWidth = max(6, 4.5 * nStim);
    fig = figure('Units', 'inches', 'Position', [1 1 figWidth 8]);
    tl = tiledlayout(2, nStim, 'TileSpacing', 'compact', 'Padding', 'compact');
    title(tl, sprintf('%s, chan %d, %s: pre (block %d) vs post (block %d)', ...
        sid, chanInt, condLabel, preBlock, postBlock), ...
        'FontSize', 14, 'FontWeight', 'bold');

    % --- Row 1: mean only (one panel per stim level) ---
    for sIdx = 1:nStim
        condInt = stimInterest(sIdx);
        nexttile(sIdx); hold on
        if condInt > length(entry.stimLevelUniq)
            title(sprintf('Stim level %d (unavailable)', condInt));
            continue
        end
        stimmA     = entry.stimLevelUniq(condInt) / 1e3;
        preTrials  = squeeze(entry.epochsEPblock{preIdx}{condInt}(:, chanInt, :));
        postTrials = squeeze(entry.epochsEPblock{postIdx}{condInt}(:, chanInt, :));
        plot(entry.tEpoch, 1e6*mean(preTrials, 2),  'LineWidth', 2, 'Color', preCol);
        plot(entry.tEpoch, 1e6*mean(postTrials, 2), 'LineWidth', 2, 'Color', postCol);
        xlim(xLimMs); ylim(yLimUV);
        xlabel('time (ms)'); ylabel('Voltage (\muV)');
        title(sprintf('Stim %d (%.1f mA) mean (n pre=%d, post=%d)', ...
            condInt, stimmA, size(preTrials, 2), size(postTrials, 2)));
        legend({'pre', 'post'}, 'Location', 'best');
        set(gca, 'FontSize', 12)
        line1 = vline(entry.tBegin, 'k:'); set(line1, 'tag', 'vline', 'handlevisibility', 'off')
        line2 = vline(entry.tEnd,   'k:'); set(line2, 'tag', 'vline', 'handlevisibility', 'off')
    end

    % --- Row 2: mean + 95% CI (one panel per stim level) ---
    for sIdx = 1:nStim
        condInt = stimInterest(sIdx);
        nexttile(nStim + sIdx); hold on
        if condInt > length(entry.stimLevelUniq)
            title(sprintf('Stim level %d (unavailable)', condInt));
            continue
        end
        stimmA     = entry.stimLevelUniq(condInt) / 1e3;
        preTrials  = squeeze(entry.epochsEPblock{preIdx}{condInt}(:, chanInt, :));
        postTrials = squeeze(entry.epochsEPblock{postIdx}{condInt}(:, chanInt, :));
        plotBTLError(entry.tEpoch(:)', 1e6*preTrials,  'CI', preCol(:));
        plotBTLError(entry.tEpoch(:)', 1e6*postTrials, 'CI', postCol(:));
        xlim(xLimMs); ylim(yLimUV);
        xlabel('time (ms)'); ylabel('Voltage (\muV)');
        title(sprintf('Stim %d (%.1f mA) mean + 95%% CI', condInt, stimmA));
        h = flipud(findobj(gca, 'Type', 'line'));
        if length(h) >= 2
            legend(h([1 2]), {'pre', 'post'}, 'Location', 'best');
        end
        set(gca, 'FontSize', 12)
        line1 = vline(entry.tBegin, 'k:'); set(line1, 'tag', 'vline', 'handlevisibility', 'off')
        line2 = vline(entry.tEnd,   'k:'); set(line2, 'tag', 'vline', 'handlevisibility', 'off')
    end

    if savePlot
        stimStr = strjoin(arrayfun(@num2str, stimInterest, 'UniformOutput', false), '_');
        figName = sprintf('pre_post_%s_chan%d_%s_block%d_vs_%d_stim%s', ...
            sid, chanInt, regexprep(condLabel, '[\s\/]', '_'), ...
            preBlock, postBlock, stimStr);
        SaveFig(OUTPUT_DIR, figName, 'png', '-r600');
    end
end

fprintf('\nDone. %d cases plotted.\n', size(cases, 1));
